/* QUESTION 1
SELECT EXTRACT(YEAR FROM C.COLLISION_DATE) as year, COUNT(C.COLLISION_DATE) as num_collision FROM COLLISION C GROUP BY EXTRACT(YEAR FROM C.COLLISION_DATE)
)*/

/* QUESTION 2
SELECT * FROM (SELECT P.VEHICLE_MAKE, COUNT(P.VEHICLE_MAKE) FROM PARTY P GROUP BY P.VEHICLE_MAKE ORDER BY (COUNT(P.VEHICLE_MAKE)) DESC) WHERE ROWNUM <= 1
*/

/* QUESTION 3
 SELECT SUM(C1.FRAC) FROM (SELECT C.LIGHTING AS light,COUNT(C.LIGHTING)/(SELECT COUNT(*) FROM COLLISION) AS frac 
 FROM COLLISION C GROUP BY(C.LIGHTING)) C1 WHERE LIGHT LIKE '%dark%'
 */
 
 /* Question 4
SELECT COUNT(C.WEATHER_1)+COUNT(C.WEATHER_2) FROM COLLISION C WHERE (C.WEATHER_1 = 'snowing' OR C.WEATHER_2 = 'snowing')
*/

/* Question 5
SELECT * FROM (SELECT to_char(C.COLLISION_DATE,'DAY') , COUNT(C.COLLISION_DATE) AS num FROM COLLISION C GROUP BY to_char(C.COLLISION_DATE,'DAY') ORDER BY num DESC) WHERE ROWNUM <=1
*/
 
 
 /* Question 6 
SELECT WEATHER_1 as weather,CT1+CT2 as count FROM (SELECT C.WEATHER_1,COUNT(*) as ct1 FROM COLLISION C GROUP BY (C.WEATHER_1)) C1
LEFT OUTER JOIN (SELECT C2.WEATHER_2,COUNT(*) as ct2 FROM COLLISION C2 GROUP BY (C2.WEATHER_2)) C2 ON  C1.WEATHER_1 = C2.WEATHER_2
 */
