/* QUESTION 1
SELECT EXTRACT(YEAR FROM C.COLLISION_DATE) as year, COUNT(C.COLLISION_DATE) as num_collision FROM COLLISION C GROUP BY EXTRACT(YEAR FROM C.COLLISION_DATE)
)*/

/* QUESTION 2
 SELECT P.VEHICLE_MAKE, COUNT(P.VEHICLE_MAKE)
 FROM PARTY P GROUP BY P.VEHICLE_MAKE 
 ORDER BY (COUNT(P.VEHICLE_MAKE)) DESC 
 FETCH FIRST 1 ROW ONLY
 */

/* QUESTION 3
 SELECT SUM(C1.FRAC) FROM (SELECT C.LIGHTING AS light,COUNT(C.LIGHTING)/(SELECT COUNT(*) FROM COLLISION) AS frac 
 FROM COLLISION C GROUP BY(C.LIGHTING)) C1 WHERE LIGHT LIKE '%dark%'
 */
 
 /* Question 4
SELECT WEATHER_1 AS WEATHER, COUNT(WEATHER_1) AS COUNT 
FROM ((SELECT C.CASE_ID, C.WEATHER_1 FROM COLLISION C) UNION (SELECT C.CASE_ID, C.WEATHER_2 FROM COLLISION C) )
WHERE WEATHER_1 = ('snowing') 
GROUP BY WEATHER_1
*/

/* Question 5
SELECT to_char(C.COLLISION_DATE,'DAY') AS DAY, COUNT(C.COLLISION_DATE) AS num 
FROM COLLISION C 
GROUP BY to_char(C.COLLISION_DATE,'DAY') 
ORDER BY num DESC
FETCH FIRST 1 ROW ONLY 
*/
 
 
 /* Question 6 
SELECT WEATHER_1 AS WEATHER, COUNT(WEATHER_1) AS COUNT 
FROM ((SELECT C.CASE_ID, C.WEATHER_1 FROM COLLISION C) UNION (SELECT C.CASE_ID, C.WEATHER_2 FROM COLLISION C) )
WHERE WEATHER_1 != ('null') 
GROUP BY WEATHER_1
ORDER BY COUNT DESC
*/
